### ISSUE TITLE
Problem during inference

### ISSUE THREAD

**Issue by Utkarsh-quytech** [CV-ZMH/human_activity_recognition#12]
While running the demo.py on wideresnet_mars.pth or siamesenet_mars.pth the terminal gets stuck unless i close the video window, then % increases and then after some windows are closed it starts giving the below error.
Any help is much appreciated, Thanks!!

(humanaction) C:\Users\Utkarsh.Singh\Documents\Utkarsh\PoseTracking\human-action-recognition\src>python demo.py --task action --source ../test_data/fun_theory.mp4 --save_folder ../output --debug_track
pycuda or tensorrt not installed.
[INFO] Loading pytorch trtpose model with "../weights\pose_estimation\trtpose\densenet121_baseline_att_256x256_B_epoch_160.pth"
[INFO] Loading pytorch reid model: ../weights\tracker\deepsort\wideresnet_mars.pth.
[INFO] Writing output to ../output\fun_theory_trtpose_deepsort_mars_wideresnet_dnn_torch.avi
[INFO] Writing output to ../output\fun_theory_trtpose_deepsort_mars_wideresnet_dnn_torch_debug.avi
Run | fun_theory.mp4 ----------------------------------------   0% -:--:-- 66.85fps[INFO] Saving video to : ../output\fun_theory_trtpose_deepsort_mars_wideresnet_dnn_torch.avi
Run | fun_theory.mp4 ---- -----------------------------------  11% -:--:-- 0.03fps
Traceback (most recent call last):
  File "demo.py", line 138, in <module>
    main()
  File "demo.py", line 98, in main
    predictions = action_classifier.classify(predictions)
  File "C:\Users\Utkarsh.Singh\Documents\Utkarsh\PoseTracking\human-action-recognition\src\lib\classifier\dnn\classifier.py", line 70, in classify
    self.dict_id2clf[id] = self._create_classifier(id)
  File "C:\Users\Utkarsh.Singh\Documents\Utkarsh\PoseTracking\human-action-recognition\src\lib\classifier\dnn\classifier.py", line 53, in <lambda>
    model_path, classes, window_size, human_id, threshold=threshold)
  File "C:\Users\Utkarsh.Singh\Documents\Utkarsh\PoseTracking\human-action-recognition\src\lib\classifier\dnn\classifier.py", line 172, in __init__
    self.model = pickle.load(f)
ModuleNotFoundError: No module named 'sklearn.neighbors._classification'

**Comment by Utkarsh-quytech** [comment]
I was not able to install TensorRT so can't convert the model to .trt, so how can i run the demo without converting the model?

**Comment by Raven19888** [comment]
I'm having the same problem, which seems to be due to an incompatibility with the scikit-learn version, but I haven't found a solution yet

**Comment by PabloMurrieta** [comment]
> I'm having the same problem, which seems to be due to an incompatibility with the scikit-learn version, but I haven't found a solution yet
I'm having the same problem, were you able to find the solution?
